-- Superseded by 006_co_buyer_index_covering.sql: the covering variant
-- idx_trades_token_type_wallet_time replaces this index and serves the
-- co-buyer scanner directly from the index. Keeping this file as a no-op
-- comment preserves the migration ordering for any environment that already
-- ran the original CREATE; migration 006 issues DROP IF EXISTS to clean up.
